# Generated by Django 4.2.2 on 2023-07-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('add_blog', 'Can add blog'),)},
        ),
    ]
